import "dotenv/config";

export const ENV  = {

BACKEND_SIGNUP_URL:process.env.NEXT_PUBLIC_BACKEND_SIGNUP_URL,
BACKEND_SIGNIN_URL:process.env.NEXT_PUBLIC_BACKEND_SIGNIN_URL,
BACKEND_SIGNOUT_URL:process.env.NEXT_PUBLIC_BACKEND_SIGNOUT_URL,
BACKEND_UPDATE_URL:process.env.NEXT_PUBLIC_BACKEND_UPDATE_URL,
BACKEND_ME_URL:process.env.NEXT_PUBLIC_BACKEND_ME_URL

}